---
#
# Copyright 2020 The Magma Authors.

# This source code is licensed under the BSD-style license found in the
# LICENSE file in the root directory of this source tree.

# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License

- name: disable the firewall
  systemd: 
     name: firewalld
     state: stopped
     enabled: false
  ignore_errors: true

- name: set the hostname for the machine
  become: true
  copy:
   content: "{{ 'xwfm.' + partner + '.' + env + '.' + server_id | default('1') }}"
   dest: /etc/hostname
  ignore_errors: true

- name: set the hostname now
  become: true
  shell: hostname {{ 'xwfm.' + partner + '.' + env + '.' + server_id | default('1') }}
  ignore_errors: true

- name: delete ovs bridges incase they exist
  become: true
  shell: ovs-vsctl del-br {{ item }}
  with_items:
     - uplink_br0
     - cwag_br0
  ignore_errors: true

- name: Create OVS bridge cwag_br0 and GRE tunnel gre0
  become: true
  script: create_gre_tunnel.sh

- name: Configure Red Hat interfaces
  when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'
  include_tasks: redhat.yml

- name: Configure Ubuntu interfaces
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
  include_tasks: debian.yml

- name: Enable IP forwarding
  become: true
  sysctl: name="net.ipv4.ip_forward" value=1 sysctl_set=yes state=present reload=yes

- name: Set OVS controller for XWF bridge
  become: true
  shell: ovs-vsctl set-controller uplink_br0 tcp:{{ xwf_ctrl_ip }}:6653

